### ISSUE TITLE
rustfmt settings (linebender-wide?)

### ISSUE THREAD

**Issue by simbleau** [linebender/vello#510]
In setting up the seed for vello_svg, a comment came up that there's a fragmented story around rustfmt.toml settings across linebender.

"Kurbo, Glazier, Druid, and Piet have the following. Vello and Xilem right now don't have the file at all. I think going with the Kurbo one is fine." - @xStrom 

```toml
max_width = 100
use_field_init_shorthand = true
newline_style = "Unix"
```

And I'd love to add the following, which keeps imports very tidy: 
```toml
imports_granularity = "Crate"
```

Is this something that needs more discussion or can I chug along with a PR to add all of these settings?
