### ISSUE TITLE
Serde support for re-exported Peniko types

### ISSUE THREAD

**Issue by timtom-dev** [linebender/vello#614]
Peniko has a "serde" feature flag that derives serialization for its types. Vello re-exports Peniko, but doesn't have a serde flag. So, if you use the Peniko exported from Vello, there's no way to enable serde for those types.

**Comment by DJMcNab** [comment]
Vello does not currently directly support serialisation - I think if we were to create a `serde` flag, it would when we added actual support for doing serialisation properly.

I'd recommend using:
```toml
[dependencies]
vello = "..."
peniko = { version = "*", default-features = false, features = ["serde"] }
```
in the near term, which should enable what you need.
Using a `"*"` dependency is not normally what you want, but in this case you want the version to be selected by Vello.
